productos:
    resource: "@ProductosBundle/Resources/config/routing.yml"
    prefix:   /

emm_user:
    resource: "@EMMUserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
